//
// © Copyright 2012 Carlos Quiroz. All rights reserved.
// All trademarks and service marks are the properties of their respective owners.

"use strict";

//
// This script is called when the devtools are opened
// We first try to detect if the inspected page contains a css file
// generated by Saas, and in that case a developer sidbar is opened
// Inspect the resources on the inspected window
chrome.devtools.inspectedWindow.getResources(setupSassSidebar);
var tabId = chrome.devtools.inspectedWindow.tabId;

/**
 * Called upon Developer Tools is opened with the list of the resources in the page
 * This function tries to determine if there are css files made using sass
 */
function setupSassSidebar(resources) {
    var cssResources = findCssResources(resources);
    findSassResources(cssResources);
}

/**
 * Finds what files are css on the resources list
 */
function findCssResources(resources) {
    var cssResources = [];
    for (var i = 0; i < resources.length; i++) {
        // We decide that the files ending with css are the ones assumed to be css
        // It could be better to actually parse the resource
        if (resources[i].url.search('\\.css') > 0) {
            cssResources.push(resources[i]);
        }
    }
    return cssResources;
}

/**
 * Read the css file content and try to find saas debugging information
 */
function findSassResources(cssResources) {
    var sassResources = [];
    var resourcesParsed = 0;
    for (var i = 0; i < cssResources.length; i++) {
        // Load each resources. The getContent call is asynchronous
        cssResources[i].getContent(function(content) {
            // Search for the marker of debug info
            if (content.search('-sass-debug-info') > 0) {
                sassResources.push(cssResources[i]);
            }
            resourcesParsed = resourcesParsed + 1;
            if (resourcesParsed === cssResources.length) {
                // Completed parsing of all css resources
                if (sassResources.length > 0) {

                    chrome.extension.sendRequest({ tabId: tabId }, function(results) {
                        buildSidebar(results);
                    });
                }
            }
        });
    }
}

/**
 * Functions that is called using evaluation and returns a JSON element
 * that is displayed on the sidebar
 *
 * As the function is evaluated as a string it cannot call other functions on
 * the file
 */
var pageFindSassInfo = function(element) {
    try {
        // $0 contains the element selected
        var data = $0;
        var sassValues = JSON.parse(element);
        var copy = {
            __proto__: null
        };
        // Extract the matched css rules
        var rules = window.getMatchedCSSRules(data, '');
        if (rules) {
            for (var j = 0;j<rules.length;j++) {
                // If some of the rules matches a sass debug info add it to the content
                // of the sidebar
                if (typeof sassValues[rules[j].selectorText] !== 'undefined') {
                    var className = rules[j].selectorText;
                    // Divide using commas to show only one matching class per
                    // line
                    var splittedClass = className.split(", ");
                    for (var k = 0;k<splittedClass.length;k++) {
                        // use only the file name, not the full path
                        var fileName = sassValues[className].filename.replace(/^.*[\\\/]/, '');
                        var linenum = sassValues[className].linenum;
                        // Get the debug info in the form of filename:linenum
                        var sassDebug =  fileName + ':' + linenum;
                        //copy[className] = sassDebug;
                        copy[splittedClass[k]] = sassDebug;
                    }
                }
            }
        }
        return copy;
    } catch(err) {
       return {'error': "Error description: " + err.message };
    }
};

/**
 * Creates the sidebar
 */
function buildSidebar(pageContents) {
    chrome.devtools.panels.elements.createSidebarPane("SASS", function(sidebar) {
        // on version 0.2 we display a page containing all found sass styles
        // sass has been found
        function updateElementProperties() {
            try {
                // The expression is a function text where we pass the parameter
                // and it is executed in the context of the elements panel
                // The page contents need to be passed as a string and re-parsed
                // inside
                var expression = "(" + pageFindSassInfo.toString() + ")('" + JSON.stringify(pageContents) + "');";
                sidebar.setExpression(expression);
            } catch (error) {
                sidebar.setObject({error: error.message});
            }
        }
        chrome.devtools.panels.elements.onSelectionChanged.addListener(updateElementProperties);
    });
}

