//
// © Copyright 2012 Carlos Quiroz. All rights reserved.
// All trademarks and service marks are the properties of their respective owners.
//

// This script is called when the devtools are opened
// We first try to detect if the inspected page contains a css file
// generated by Saas, and in that case a developer sidbar is opened

// Inspect the resources on the inspected window
chrome.devtools.inspectedWindow.getResources(function(resources) {
  var cssResources = [];
  for (var i=0;i<resources.length;i++) {
    // We decide that the files ending with css are the ones assumed to be css
    // It could be better to actually parse the resource
    if (resources[i].url.search('\\.css') > 0) {
      cssResources.push(resources[i]);
    }
  }
});
